### ISSUE TITLE
ref() or reactive Translations

### ISSUE THREAD

**Issue by abemscac** [abemscac/pies-doc#48]
- [ ] ref() or reactive - 繁體中文
- [ ] ref() or reactive - 简体中文
- [ ] ref() or reactive - 한국어
- [ ] ref() or reactive - 日本語
